language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - python -m pip install .

script:
  - python test/cli/G5check.py
  - python test/cli/G5compare.py
  - python test/cli/G5list.py
  - python test/cli/G5print.py
  - python test/cli/G5repair.py
  - python test/cli/G5repack.py

