language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - python -m pip install .

script:
  - python test/bin/G5check.py
  - python test/bin/G5compare.py
  - python test/bin/G5list.py
  - python test/bin/G5repair.py

