language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install h5py numpy docopt
  - pip install .
  - export PATH="${PWD}"/bin:"${PATH}"
  - chmod +x ./test/bin/G5check
  - chmod +x ./test/bin/G5compare
  - chmod +x ./test/bin/G5list
  - chmod +x ./test/bin/G5repair
# command to run tests
script:
  - cd test/bin
  - ./G5check
  - ./G5compare
  - ./G5list
  - ./G5repair
  - cd ../..

